### ISSUE TITLE
RH Chemistry 1.34 crashes on start with a dedicated server

### ISSUE THREAD

**Issue by belathus** [GlobbyPotato/RH-chemistry#2]
I get the following crash when starting a dedicated server with RH Chemstry version 1.34: https://gist.github.com/belathus/dc58716e2dcc50741bfc76c63de21078

Reverting to 1.33 does not crash.
Minecraft 1.10.2
Forge version 12.18.3.2239

**Comment by GlobbyPotato** [comment]
Thanks for reporting. It looks like something was accidentally called on the wrong side.
Did a fix, it should launch now.
